install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
#- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
#- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${CXX}
- ${CXX} --version
#addons:
  #apt:
    ## List of whitelisted in travis packages for ubuntu-precise can be found here:
    ##   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    ## List of whitelisted in travis apt-sources:
    ##   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    #sources:
    #- ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.7
    #packages:
    #- gcc-4.9
    #- g++-4.9
    #- clang-3.7
    #- valgrind
language: cpp
compiler:
    - gcc
    #- clang
script:
    if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./travis.sh ; fi
sudo: false
notifications:
    email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JefWi4aLpXvl8xsXtuSijbvbDObuPbGipk5Mh/6spyTP2k2XHEYa74QOL3MSdqtsbzd5awlEXauY20SEzw7BtcVpXER8K93kTnrEK+Y1tLdIjagvZnojG4yzp2g0SKMRMOoR+n/Hi9X0nDzO/g/2+XxTDDfBiDf2vc2ozGPjvK0u8U0gcXapuT7d9ETFIPbM6U9e99j6kyr7i2VxFMzaQXbEk44C2PJtfql4rhqGRaX1MkHgo21pqQt7JfuglGXX0DF1Eex6SEFDF71SGV9b7dP/CMhp2aKs1ZpyjwfRn6WRJ0ouUiWwK7YseOPYxI2aIAGg17d3vDRAdf3vnUfS0FSwNahPQnAofpDJ2sMBlkZP5kzkOoVSi4tqE8mVuNml6tFlZL/+Q4cepjeGVZyBj+AfkYEmL6YzuOOIIeaHfvpcPUZ28XcSuyItRNEjBYcPY2OmcAEYqukRG6kKYqsHyI20oqlJx1O74n2HhH3miDYwzuVYblqUceSrHbncNNmRsU6t1XMi2aF/KftCwDZ7JTIq7iQxLUz+7T1UYp86reeAg8XvEMvJyflXwBNZl76DPrPoYBa0MI4hbi+MocOeTNbQ7m6K+sB8DADrZBBFSMrAewnRdPRtICy9BGuXF7X9z+Jt9xg2kGe/CF5QJGZH6lQyhxDl87kPg9FXwEjDOdI="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Rich143/Flight_Controller"
      description: "<Your project description here>"
    notification_email: richard.arnold.matthews@gmail.com
    build_command:   make
    branch_pattern: coverity_scan
