#ifndef PINS_H_
#define PINS_H_

#include "stm32f4xx_hal.h"

#ifdef FC
#define LED_G_PIN GPIO_PIN_15
#define LED_G_PORT GPIOB
#define LED_R_PIN GPIO_PIN_9
#define LED_R_PORT GPIOC
#define LED_B_PIN GPIO_PIN_8
#define LED_B_PORT GPIOC

#define LED1_PIN GPIO_PIN_12
#define LED2_PIN GPIO_PIN_13
#define LED3_PIN GPIO_PIN_14
#define LED_PORT GPIOB

#define LED1_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED1_PIN);
#define LED1_ON HAL_GPIO_WritePin(LED_PORT, LED1_PIN, GPIO_PIN_SET);
#define LED1_OFF HAL_GPIO_WritePin(LED_PORT, LED1_PIN, GPIO_PIN_RESET);

#define LED2_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED2_PIN);
#define LED2_ON HAL_GPIO_WritePin(LED_PORT, LED2_PIN, GPIO_PIN_SET);
#define LED2_OFF HAL_GPIO_WritePin(LED_PORT, LED2_PIN, GPIO_PIN_RESET);

#define LED3_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED3_PIN);
#define LED3_ON HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_SET);
#define LED3_OFF HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_RESET);

#elif defined(NUCLEO)
#define LED_PIN GPIO_PIN_5
#define LED_PORT GPIOA

#define LED3_PIN LED_PIN

#define LED3_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED3_PIN);
#define LED3_ON HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_SET);
#define LED3_OFF HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_RESET);
#endif

#endif
