#ifndef PINS_H_
#define PINS_H_

#include "stm32f4xx_hal.h"

#ifdef FC
#define LED3_PIN GPIO_PIN_14
#define LED4_PIN GPIO_PIN_15
#define LED_PORT GPIOB

#define LED3_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED3_PIN);
#define LED3_ON HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_SET);
#define LED3_OFF HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_RESET);

#define LED4_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED4_PIN);
#define LED4_ON HAL_GPIO_WritePin(LED_PORT, LED4_PIN, GPIO_PIN_SET);
#define LED4_OFF HAL_GPIO_WritePin(LED_PORT, LED4_PIN, GPIO_PIN_RESET);

#elif defined(NUCLEO)
#define LED_PIN GPIO_PIN_5
#define LED_PORT GPIOA

#define LED3_PIN LED_PIN
#define LED4_PIN LED_PIN

#define LED3_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED3_PIN);
#define LED3_ON HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_SET);
#define LED3_OFF HAL_GPIO_WritePin(LED_PORT, LED3_PIN, GPIO_PIN_RESET);

#define LED4_TOGGLE HAL_GPIO_TogglePin(LED_PORT, LED4_PIN);
#define LED4_ON HAL_GPIO_WritePin(LED_PORT, LED4_PIN, GPIO_PIN_SET);
#define LED4_OFF HAL_GPIO_WritePin(LED_PORT, LED4_PIN, GPIO_PIN_RESET);
#endif

#endif
